name: run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd Lab1
          dotnet build

      - name: Run tests
        run: |
          cd Lab1
          dotnet publish --self-contained -r linux-x64 -c Release
          bash runtests.sh
